name: Move issue to In Progress on milestone assignment

on:
  issues:
    types: [milestoned]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress column
        uses: fojia/action-move-issues-to-column@master
        with:
          project: 'first'
          column: 'In Progress'
          owner: 'testovayaorganizatsia'
          type: 'org'
          github_token: ${{ secrets.GITHUB_TOKEN }}
